name:                 polyscript-framework
version:              0.1.0.0
visibility:           public
id:                   polyscript-framework-0.1.0.0-inplace
key:                  polyscript-framework-0.1.0.0-inplace
maintainer:           mathew.burkitt@ditech.ai
author:               Mathew Burkitt, Dimension Technologies
synopsis:             PolyScript Framework for Haskell
description:          CRUD × Modes Architecture: Zero-boilerplate CLI development
category:             Development
abi:                  inplace
exposed:              True
exposed-modules:      PolyScript.Framework
import-dirs:
    /Users/doowell2/Source/repos/Scripts/scripts-dev/PolyScript/frameworks/haskell/dist-newstyle/build/x86_64-osx/ghc-9.12.2/polyscript-framework-0.1.0.0/build

library-dirs:
    /Users/doowell2/Source/repos/Scripts/scripts-dev/PolyScript/frameworks/haskell/dist-newstyle/build/x86_64-osx/ghc-9.12.2/polyscript-framework-0.1.0.0/build

library-dirs-static:
    /Users/doowell2/Source/repos/Scripts/scripts-dev/PolyScript/frameworks/haskell/dist-newstyle/build/x86_64-osx/ghc-9.12.2/polyscript-framework-0.1.0.0/build

dynamic-library-dirs:
    /Users/doowell2/Source/repos/Scripts/scripts-dev/PolyScript/frameworks/haskell/dist-newstyle/build/x86_64-osx/ghc-9.12.2/polyscript-framework-0.1.0.0/build

data-dir:
    /Users/doowell2/Source/repos/Scripts/scripts-dev/PolyScript/frameworks/haskell/.

hs-libraries:         HSpolyscript-framework-0.1.0.0-inplace
depends:
    sn-2.2.3.0-7f6da009 base-4.21.0.0-inplace
    bytestring-0.12.2.0-inplace containers-0.7-inplace
    ptprs-pplctv-0.19.0.0-06eb8f0a text-2.1.2-inplace time-1.14-inplace

haddock-interfaces:
    /Users/doowell2/Source/repos/Scripts/scripts-dev/PolyScript/frameworks/haskell/dist-newstyle/build/x86_64-osx/ghc-9.12.2/polyscript-framework-0.1.0.0/doc/html/polyscript-framework/polyscript-framework.haddock

haddock-html:
    /Users/doowell2/Source/repos/Scripts/scripts-dev/PolyScript/frameworks/haskell/dist-newstyle/build/x86_64-osx/ghc-9.12.2/polyscript-framework-0.1.0.0/doc/html/polyscript-framework
