using System;
using System.Collections.Generic;
using System.Net;
using System.Text;
using System.Text.RegularExpressions;

namespace Entropic.GUI.Models;

/// <summary>
/// Generates the full standalone HTML page from a list of ChatMessages.
/// Replaces the Python format_html() function.
/// </summary>
public static class HtmlFormatter
{
    /// <summary>Version marker embedded in every generated HTML. Bump when JS changes.</summary>
    public const string VersionMarker = "<!-- cchat-v10 -->";

    /// <summary>Check whether an HTML file was generated by the current HtmlFormatter version.</summary>
    public static bool IsCurrent(string htmlPath)
    {
        try
        {
            // Read just the first 512 bytes — marker is near the top
            using var fs = new System.IO.FileStream(htmlPath, System.IO.FileMode.Open,
                System.IO.FileAccess.Read, System.IO.FileShare.ReadWrite);
            var buf = new byte[512];
            var n = fs.Read(buf, 0, buf.Length);
            return System.Text.Encoding.UTF8.GetString(buf, 0, n).Contains(VersionMarker);
        }
        catch { return false; }
    }

    private static string H(string s) => WebUtility.HtmlEncode(s);

    private static string RoleLabel(ChatMessage msg) => msg.Role switch
    {
        "user" => "User",
        "assistant" => "Claude",
        "subagent_user" => "Agent Prompt",
        "subagent_assistant" => "Agent Response",
        "subagent_start" => "Agent",
        "subagent_end" => "",
        "plan" or "plan_summary" => "Plan",
        "task" or "task_summary" => "Task",
        "cli_session_start" => "CLI Session",
        "cli_session_end" => "",
        _ => msg.Role,
    };

    private static string CssClass(ChatMessage msg)
    {
        if (msg.Cli)
            return msg.Role.Contains("user") ? "msg-cli-user" : "msg-cli-assistant";
        if (msg.Role.Contains("subagent"))
            return "msg-subagent";
        if (msg.Role is "plan" or "plan_summary")
            return "msg-plan";
        if (msg.Role is "task" or "task_summary")
            return "msg-task";
        if (msg.Role.Contains("user"))
            return "msg-user";
        return "msg-assistant";
    }

    public static string FormatHtml(
        List<ChatMessage> messages,
        string title = "",
        bool includeImages = true,
        string repoRemote = "",
        string repoPath = "")
    {
        var genTime = DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm:ss") + " UTC";
        var repoTitle = repoRemote.Length > 0 ? H(repoRemote) : H(title.Length > 0 ? title : "Chat Log");
        var pathLine = repoPath.Length > 0 ? $"<div class='repo-path'>{H(repoPath)}</div>" : "";

        var sb = new StringBuilder(messages.Count * 500);

        sb.AppendLine("<!DOCTYPE html>").AppendLine(VersionMarker);
        sb.Append("<html><head><meta charset='utf-8'><title>").Append(H(title.Length > 0 ? title : "Chat Log")).AppendLine("</title>");
        sb.AppendLine(Css);
        sb.AppendLine("</head><body>");

        // Titlebar — single row matching AXAML toolbar
        sb.Append("<div id='titlebar'>");
        sb.Append("<span class='title-name'>").Append(repoTitle).Append("</span>");
        if (repoPath.Length > 0)
            sb.Append("<span class='repo-path'>").Append(H(repoPath)).Append("</span>");
        sb.Append("<span class='gen-time'>").Append(genTime).Append("</span>");
        sb.Append("<span class='spacer'></span>");
        sb.Append("<div class='controls'>");
        sb.Append("<input type='text' id='search-box' placeholder='Search...' oninput='doSearch(this.value)' />");
        sb.Append("<div class='filters'>");
        sb.Append("<label><input type='checkbox' id='flt-cli' onchange='toggleFilter(\"cli\",this.checked)'>CLI</label>");
        sb.Append("<label><input type='checkbox' id='flt-plans' checked onchange='toggleFilter(\"plans\",this.checked)'>Plans</label>");
        sb.Append("<label><input type='checkbox' id='flt-tasks' checked onchange='toggleFilter(\"tasks\",this.checked)'>Tasks</label>");
        sb.Append("<label><input type='checkbox' id='flt-subagents' checked onchange='toggleFilter(\"subagents\",this.checked)'>Subagents</label>");
        sb.Append("</div>");
        sb.Append("<span style='font-size:10px;color:var(--fg-dim);margin:0 3px 0 0'>Last</span>");
        sb.Append("<input type='number' id='msg-limit' value='200' min='1' style='width:52px;background:var(--search-bg);border:1px solid var(--search-border);border-radius:4px;padding:0 3px;font-size:10px;color:var(--fg);text-align:center;height:22px;box-sizing:border-box' title='Number of messages to show (from most recent)' onchange='applyMessageLimit(this.value)'/>");
        sb.Append("<span id='msg-limit-label' style='font-size:9px;color:var(--fg-dim);margin:0 0 0 4px'></span>");
        sb.Append("<span class='sep'></span>");
        sb.Append("<button class='tb-btn' onclick='toggleCollapse()' id='collapse-btn' title='Collapse/expand Claude responses'>&#9776;</button>");
        sb.Append("<button class='tb-btn' onclick='toggleTheme()' id='theme-btn' title='Toggle light/dark theme'>&#x2600;</button>");
        sb.Append("<div id='prompt-nav'>");
        sb.Append("<button onclick='navPrompt(-1)' title='Previous prompt (Alt+Up)'>&#9650;</button>");
        sb.Append("<span class='counter' id='nav-counter'>- / -</span>");
        sb.Append("<button onclick='navPrompt(1)' title='Next prompt (Alt+Down)'>&#9660;</button>");
        sb.Append("</div>");
        sb.Append("<span class='sep'></span>");
        sb.Append("<button class='tb-btn' onclick='copyConversation(\"md\")' title='Copy as Markdown'>&#x29C9;<small>md</small></button>");
        sb.Append("<button class='tb-btn' onclick='copyConversation(\"text\")' title='Copy as plain text'>&#x29C9;<small>txt</small></button>");
        sb.Append("<button class='tb-btn' onclick='copyConversation(\"html\")' title='Copy as HTML'>&#x29C9;<small>htm</small></button>");
        sb.Append("<span class='sep'></span>");
        sb.Append("<button class='tb-btn' onclick='saveConversation(\"md\")' title='Save as Markdown'>&#x2913;<small>md</small></button>");
        sb.Append("<button class='tb-btn' onclick='saveConversation(\"text\")' title='Save as plain text'>&#x2913;<small>txt</small></button>");
        sb.Append("<button class='tb-btn' onclick='saveConversation(\"html\")' title='Save as HTML'>&#x2913;<small>htm</small></button>");
        sb.Append("<span class='sep'></span>");
        sb.Append("<button class='tb-btn' id='screenshot-btn' title='Screenshot'>&#x1F4F7;</button>");
        sb.Append("<label class='follow-label'><input type='checkbox' id='follow-chk' onchange='toggleFollow(this.checked)'>Follow</label>");
        sb.Append("</div></div>");

        // Content area: timeline on left, messages on right
        sb.AppendLine("<div id='content-area'>");
        sb.AppendLine("<div id='timeline'></div>");
        sb.AppendLine("<div id='messages'>");

        // Messages
        var openDetails = 0;
        var msgIdx = 0;
        string? prevGroupKey = null;
        var bubbleOpen = false;

        void CloseBubble()
        {
            if (bubbleOpen)
            {
                sb.Append("</div>");
                bubbleOpen = false;
            }
            prevGroupKey = null;
        }

        foreach (var msg in messages)
        {
            var ts = msg.Timestamp ?? "";
            var tsShort = ts.Length >= 19 ? ts[..19] : ts;
            var tsHtml = ts.Length > 0 ? $"<span class='timestamp'>{H(tsShort)}</span>" : "";
            var tsAttr = ts.Length > 0 ? H(tsShort) : "";

            if (msg.Role == "subagent_start")
            {
                CloseBubble();
                sb.Append($"<details open data-role='subagent_start'><summary>{tsHtml}{H(msg.Text)}</summary><div class='inner'>");
                openDetails++;
                continue;
            }
            if (msg.Role == "subagent_end")
            {
                CloseBubble();
                if (openDetails > 0) { sb.Append("</div></details>"); openDetails--; }
                continue;
            }
            if (msg.Role == "cli_session_start")
            {
                CloseBubble();
                sb.Append($"<details data-role='cli_session_start'><summary class='msg msg-cli'>{tsHtml}{H(msg.Text)}</summary><div class='inner'>");
                openDetails++;
                continue;
            }
            if (msg.Role == "cli_session_end")
            {
                CloseBubble();
                if (openDetails > 0) { sb.Append("</div></details>"); openDetails--; }
                continue;
            }

            var label = RoleLabel(msg);
            var cssClass = CssClass(msg);
            var cliBadge = msg.Cli ? "<span class='cli-badge'>CLI</span>" : "";
            var textHtml = MarkdownToHtml(msg.Text);

            // Inline images
            if (includeImages && msg.Images is not null)
            {
                for (var i = 0; i < msg.Images.Count; i++)
                {
                    var img = msg.Images[i];
                    var imgTag = $"<img src='data:{img.MediaType};base64,{img.Data}' style='max-width:100%;border-radius:6px;margin:8px 0;'>";
                    textHtml = textHtml.Replace($"\x00IMG{i}\x00", imgTag);
                }
            }
            else
            {
                textHtml = Regex.Replace(textHtml, @"\x00IMG\d+\x00", "");
            }

            var rawTextAttr = H(msg.Text).Replace("'", "&#39;").Replace("\n", "&#10;");
            var groupKey = cssClass;
            var isContinuation = groupKey == prevGroupKey && bubbleOpen;

            if (isContinuation)
            {
                sb.Append($"<div class='msg-cont' id='msg-{msgIdx}' data-role='{msg.Role}' data-ts='{tsAttr}' data-text='{rawTextAttr}'>");
                sb.Append(CopyBarHtml);
                sb.Append($"<div class='cont-ts'>{tsHtml}</div>");
                sb.Append($"<div class='content'>{textHtml}</div>");
                sb.Append("</div>");
            }
            else
            {
                CloseBubble();
                sb.Append($"<div class='msg {cssClass}' id='msg-{msgIdx}' data-role='{msg.Role}' data-ts='{tsAttr}' data-text='{rawTextAttr}'>");
                sb.Append(CopyBarHtml);
                sb.Append($"<div class='role'>{H(label)}{cliBadge} {tsHtml}</div>");
                sb.Append($"<div class='content'>{textHtml}</div>");
                bubbleOpen = true;
                prevGroupKey = groupKey;
            }

            msgIdx++;
        }

        CloseBubble();
        for (var i = 0; i < openDetails; i++)
            sb.Append("</div></details>");

        sb.AppendLine("</div></div>"); // close #messages and #content-area
        sb.AppendLine(Script);
        sb.AppendLine("</body></html>");
        return sb.ToString();
    }

    // -----------------------------------------------------------------------
    // Markdown -> HTML (minimal: code blocks, inline code, bold, paragraphs)
    // -----------------------------------------------------------------------

    private static readonly Regex CodeBlockRe = new(
        @"```(\w*)\n(.*?)```", RegexOptions.Singleline | RegexOptions.Compiled);

    public static string MarkdownToHtml(string text)
    {
        var codeBlocks = new List<string>();

        text = CodeBlockRe.Replace(text, m =>
        {
            var lang = m.Groups[1].Value;
            var code = m.Groups[2].Value.Trim();
            var highlighted = HighlightCode(code, lang);
            var idx = codeBlocks.Count;
            codeBlocks.Add($"<pre><code>{highlighted}</code></pre>");
            return $"\x00CODE{idx}\x00";
        });

        // HTML-escape prose (code blocks already handled)
        text = H(text);

        // Split into paragraphs
        var paragraphs = Regex.Split(text, @"\n{2,}");
        var htmlParts = new List<string>();

        foreach (var rawPara in paragraphs)
        {
            var para = rawPara.Trim();
            if (para.Length == 0) continue;
            if (Regex.IsMatch(para, @"^\x00CODE\d+\x00$"))
            {
                htmlParts.Add(para);
                continue;
            }
            var lines = para.Split('\n');
            var formatted = new List<string>();
            foreach (var line in lines)
            {
                var l = Regex.Replace(line, @"`([^`]+)`", "<code>$1</code>");
                l = Regex.Replace(l, @"\*\*(.+?)\*\*", "<strong>$1</strong>");
                formatted.Add(l);
            }
            htmlParts.Add($"<p>{string.Join("<br>", formatted)}</p>");
        }

        text = string.Join("\n", htmlParts);

        // Restore code blocks
        for (var i = 0; i < codeBlocks.Count; i++)
            text = text.Replace($"\x00CODE{i}\x00", codeBlocks[i]);

        return text;
    }

    // -----------------------------------------------------------------------
    // Basic syntax highlighting
    // -----------------------------------------------------------------------

    private static readonly Regex CommentSlashRe = new(
        @"(//.*?)$", RegexOptions.Multiline | RegexOptions.Compiled);
    private static readonly Regex CommentHashRe = new(
        @"(#.*?)$", RegexOptions.Multiline | RegexOptions.Compiled);
    private static readonly Regex StringDquoteRe = new(
        @"(&quot;)(.*?)(&quot;)", RegexOptions.Compiled);
    private static readonly Regex StringSquoteRe = new(
        @"(&#x27;)(.*?)(&#x27;)", RegexOptions.Compiled);
    private static readonly Regex NumberRe = new(
        @"\b(\d+\.?\d*)\b", RegexOptions.Compiled);
    private static readonly Regex KeywordRe = new(
        @"\b(def|class|if|elif|else|for|while|return|import|from|in|not|and|or|is|None|True|False" +
        @"|function|const|let|var|async|await|try|catch|except|finally|raise|yield" +
        @"|public|private|static|void|int|string|bool|new|this|self|null|undefined" +
        @"|sub|my|use|require|our|local)\b", RegexOptions.Compiled);

    public static string HighlightCode(string code, string lang)
    {
        code = H(code);
        code = CommentSlashRe.Replace(code, "<span class=\"cmt\">$1</span>");
        code = CommentHashRe.Replace(code, "<span class=\"cmt\">$1</span>");
        code = StringDquoteRe.Replace(code, "<span class=\"str\">$1$2$3</span>");
        code = StringSquoteRe.Replace(code, "<span class=\"str\">$1$2$3</span>");
        code = NumberRe.Replace(code, "<span class=\"num\">$1</span>");
        code = KeywordRe.Replace(code, "<span class=\"kw\">$1</span>");
        return code;
    }

    // -----------------------------------------------------------------------
    // Constant strings — CSS, JS, copy bar
    // -----------------------------------------------------------------------

    private const string CopyBarHtml =
        "<div class='copy-bar'>" +
        "<button onclick='copyMsg(this,\"text\")' title='Copy Plain Text'>T</button>" +
        "<button onclick='copyMsg(this,\"md\")' title='Copy Markdown'>M</button>" +
        "<button onclick='copyMsg(this,\"html\")' title='Copy HTML'>&lt;/&gt;</button>" +
        "<button onclick='copyMsg(this,\"rich\")' title='Copy Rich Text'>R</button>" +
        "</div>";

    private const string Css = @"
    <style>
        :root {
          --bg: #f5f5f5; --fg: #1a1a1a; --fg-muted: #555; --fg-dim: #999;
          --bar-bg: #fff; --bar-border: #ddd;
          --user-bg: #d1e7ff; --asst-bg: #fff; --asst-border: #e0e0e0;
          --sub-bg: #f0f0f0; --sub-border: #888;
          --plan-bg: #fff3cd; --plan-border: #ffc107;
          --task-bg: #d4edda; --task-border: #28a745;
          --cli-bg: #f8d7da; --cli-border: #dc3545;
          --cli-msg-bg: #fce4ec; --cli-msg-border: #e91e63;
          --code-bg: #e8e8e8; --pre-bg: #1e1e1e; --pre-fg: #d4d4d4;
          --btn-bg: #e8e8e8; --btn-border: #ccc; --btn-hover: #d0d0d0;
          --tl-bg: #e8e8e8; --tl-border: #ddd;
          --summary-bg: #e8e8e8; --detail-border: #ccc;
          --search-bg: #fff; --search-border: #ccc;
          --highlight-bg: #fff176;
          --copy-bg: rgba(255,255,255,0.9);
        }
        [data-theme=""dark""] {
          --bg: #0d1117; --fg: #c9d1d9; --fg-muted: #8b949e; --fg-dim: #6e7681;
          --bar-bg: #161b22; --bar-border: #30363d;
          --user-bg: #1a3352; --asst-bg: #161b22; --asst-border: #30363d;
          --sub-bg: #1c2128; --sub-border: #444c56;
          --plan-bg: #2a2000; --plan-border: #9e6a00;
          --task-bg: #0d2818; --task-border: #238636;
          --cli-bg: #2d1012; --cli-border: #da3633;
          --cli-msg-bg: #2a1520; --cli-msg-border: #db61a2;
          --code-bg: #30363d; --pre-bg: #161b22; --pre-fg: #c9d1d9;
          --btn-bg: #21262d; --btn-border: #30363d; --btn-hover: #30363d;
          --tl-bg: #161b22; --tl-border: #30363d;
          --summary-bg: #21262d; --detail-border: #30363d;
          --search-bg: #0d1117; --search-border: #30363d;
          --highlight-bg: #5a4a00;
          --copy-bg: rgba(22,27,34,0.95);
        }
        html, body { height: 100%; margin: 0; overflow: hidden; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
               background: var(--bg); color: var(--fg);
               display: flex; flex-direction: column; }
        #content-area { flex: 1; display: flex; overflow: hidden; }
        #messages { flex: 1; overflow-y: auto; overflow-x: hidden; padding: 10px 20px 20px 16px; }
        #messages > * { max-width: 900px; }
        .msg { margin: 12px 0; padding: 12px 16px; border-radius: 10px; line-height: 1.5;
               position: relative; }
        .msg-user { background: var(--user-bg); margin-right: 80px; }
        .msg-assistant { background: var(--asst-bg); border: 1px solid var(--asst-border); margin-left: 40px; }
        .msg-subagent { background: var(--sub-bg); border-left: 3px solid var(--sub-border); margin-left: 60px; }
        .msg-plan { background: var(--plan-bg); border-left: 3px solid var(--plan-border); }
        .msg-task { background: var(--task-bg); border-left: 3px solid var(--task-border); font-size: 0.9em; }
        .msg-cli { background: var(--cli-bg); border-left: 3px solid var(--cli-border); font-style: italic; }
        .msg-cli-user { background: var(--cli-msg-bg); border-left: 3px solid var(--cli-msg-border); margin-right: 80px; }
        .msg-cli-assistant { background: var(--cli-msg-bg); border-left: 3px solid var(--cli-msg-border); margin-left: 40px; }
        .cli-badge { display: inline-block; background: var(--cli-msg-border); color: #fff;
                     font-size: 0.7em; padding: 1px 6px; border-radius: 3px; margin-left: 6px; vertical-align: middle; }
        .role { font-weight: 600; font-size: 0.85em; color: var(--fg-muted); margin-bottom: 4px; }
        .timestamp { font-size: 0.75em; color: var(--fg-dim); float: right; }
        .content { font-size: 0.95em; }
        .content p { margin: 0.4em 0; }
        .content code { background: var(--code-bg); padding: 1px 4px; border-radius: 3px; font-size: 0.9em; }
        .content pre { background: var(--pre-bg); color: var(--pre-fg); padding: 12px;
                        border-radius: 6px; overflow-x: auto; white-space: pre; }
        .content pre code { background: transparent; color: inherit; padding: 0; border-radius: 0; }
        .content pre .kw { color: #569cd6; }
        .content pre .str { color: #ce9178; }
        .content pre .num { color: #b5cea8; }
        .content pre .cmt { color: #6a9955; font-style: italic; }
        .content pre .punct { color: var(--pre-fg); }
        .content pre .key { color: #9cdcfe; }
        details { margin: 8px 0 8px 40px; }
        details summary { cursor: pointer; font-weight: 600; color: var(--fg-muted); padding: 6px;
                          background: var(--summary-bg); border-radius: 6px; }
        details .inner { border-left: 2px solid var(--detail-border); padding-left: 12px; margin-top: 8px; }
        #titlebar { flex-shrink: 0; background: var(--bar-bg);
                    border-bottom: 2px solid var(--bar-border); padding: 4px 8px;
                    display: flex; flex-wrap: wrap; align-items: center; gap: 8px;
                    font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif; }
        #titlebar .title-name { font-weight: bold; font-size: 12px; color: var(--fg); white-space: nowrap; margin-right: 8px; }
        #titlebar .repo-path { font-size: 9px; color: var(--fg-dim); font-family: 'Cascadia Mono', Consolas, monospace;
                    max-width: 300px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; margin-right: 8px; }
        #titlebar .gen-time { font-size: 9px; color: var(--fg-dim); margin-right: 12px; }
        #titlebar .spacer { flex: 1; }
        #titlebar .controls { display: flex; gap: 4px; flex-wrap: wrap; align-items: center; }
        #titlebar .filters { display: flex; gap: 4px; flex-wrap: wrap; align-items: center; }
        #titlebar .filters label { font-size: 11px; color: var(--fg-muted); cursor: pointer;
                                   white-space: nowrap; user-select: none; }
        #titlebar .filters input[type=checkbox] { margin-right: 2px; vertical-align: middle; }
        #prompt-nav { display: flex; align-items: center; gap: 4px; }
        #prompt-nav button, .tb-btn { background: var(--btn-bg); border: 1px solid var(--btn-border);
                             border-radius: 4px; cursor: pointer; padding: 1px 5px;
                             font-size: 13px; line-height: 1; color: var(--fg-muted);
                             height: 22px; box-sizing: border-box; }
        #prompt-nav button:hover, .tb-btn:hover { background: var(--btn-hover); }
        #prompt-nav .counter { font-size: 11px; color: var(--fg-dim); min-width: 45px; text-align: center; }
        #search-box { background: var(--search-bg); border: 1px solid var(--search-border);
                      border-radius: 4px; padding: 0 4px; font-size: 11px; width: 130px;
                      color: var(--fg); outline: none; height: 22px; box-sizing: border-box; }
        #search-box:focus { border-color: #4a90d9; width: 180px; transition: width 0.2s; }
        .sep { display: inline-block; width: 1px; height: 18px; background: var(--btn-border); margin: 0 6px; vertical-align: middle; }
        .tb-btn small { font-size: 9px; vertical-align: middle; }
        .follow-label { font-size: 11px; color: var(--fg-muted); cursor: pointer; white-space: nowrap; user-select: none; margin-left: 4px; }
        .follow-label input[type=checkbox] { margin-right: 2px; vertical-align: middle; }
        .copy-bar { display: none; position: absolute; top: 4px; right: 4px; gap: 2px; z-index: 10; }
        .msg:hover > .copy-bar { display: flex; }
        .copy-bar button { background: var(--copy-bg); border: 1px solid var(--btn-border);
                           border-radius: 4px; cursor: pointer; padding: 2px 5px;
                           font-size: 0.75em; line-height: 1.2; color: var(--fg-muted); }
        .copy-bar button:hover { background: var(--btn-hover); }
        .copy-bar button.copied { background: #c8f7c5; border-color: #6a5; }
        #timeline { flex-shrink: 0; width: 28px; position: relative;
                    background: var(--tl-bg); border-right: 1px solid var(--tl-border);
                    overflow: visible; }
        #timeline .marker { position: absolute; left: 3px; width: 20px; height: 5px;
                            border-radius: 3px; cursor: pointer; opacity: 0.35; transition: all 0.15s; }
        #timeline .marker:hover { opacity: 0.8; }
        #timeline .marker.active { opacity: 1; height: 9px; left: 1px; width: 24px;
                            box-shadow: 0 0 6px rgba(74,144,217,0.7); }
        #timeline .marker-user { background: #4a90d9; }
        #timeline .tl-tooltip { position: fixed; left: 36px; background: var(--bar-bg);
                    border: 1px solid var(--bar-border); border-radius: 6px; padding: 6px 10px;
                    font-size: 0.75em; color: var(--fg); width: 350px; white-space: pre-wrap;
                    word-break: break-word; box-shadow: 0 2px 8px rgba(0,0,0,0.15);
                    pointer-events: none; z-index: 300; display: none; }
        body.hide-cli details[data-role=""cli_session_start""],
        body.hide-cli .msg-cli-user,
        body.hide-cli .msg-cli-assistant { display: none; }
        body.hide-plans .msg-plan { display: none; }
        body.hide-tasks .msg-task { display: none; }
        body.hide-subagents details[data-role=""subagent_start""] { display: none; }
        body.hide-subagents .msg-subagent { display: none; }
        .msg.prompt-highlight { outline: 3px solid #4a90d9; outline-offset: 2px; transition: outline-color 0.3s; }
        mark.search-hit { background: var(--highlight-bg); color: inherit; border-radius: 2px; padding: 0 1px; }
        body.search-active .msg:not(.search-match) { opacity: 0.2; transition: opacity 0.15s; }
        .msg-cont { position: relative; padding: 4px 0 0 0;
                    border-top: 1px solid var(--asst-border); margin-top: 8px; }
        .cont-ts { font-size: 0.72em; color: var(--fg-dim); text-align: right; margin-bottom: 2px; }
        .msg-cont:hover > .copy-bar { display: flex; }
        .msg-assistant .content.collapsed { max-height: 120px; overflow: hidden;
            -webkit-mask-image: linear-gradient(to bottom, black 60%, transparent 100%);
            mask-image: linear-gradient(to bottom, black 60%, transparent 100%); }
        .collapse-toggle { font-size: 0.75em; color: var(--fg-dim); cursor: pointer;
            border: none; background: none; padding: 2px 0; margin-top: 4px; }
        .collapse-toggle:hover { color: var(--fg-muted); text-decoration: underline; }
    </style>";

    private const string Script = @"
    <script>
    (function(){
      var savedTheme = localStorage.getItem('cchat-theme') || 'light';
      if (savedTheme === 'dark') document.documentElement.setAttribute('data-theme','dark');

      function toggleTheme() {
        var isDark = document.documentElement.getAttribute('data-theme') === 'dark';
        document.documentElement.setAttribute('data-theme', isDark ? 'light' : 'dark');
        localStorage.setItem('cchat-theme', isDark ? 'light' : 'dark');
      }
      window.toggleTheme = toggleTheme;

      function toggleFilter(kind, checked) {
        document.body.classList.toggle('hide-' + kind, !checked);
        rebuildTimeline();
      }
      window.toggleFilter = toggleFilter;
      document.body.classList.add('hide-cli');

      function applyMessageLimit(val) {
        var limit = parseInt(val, 10);
        if (isNaN(limit) || limit < 1) return;
        var allMsgs = Array.from(document.querySelectorAll('.msg, .msg-cont'));
        var total = allMsgs.length;
        var hide = Math.max(0, total - limit);
        allMsgs.forEach(function(el, i) { el.style.display = i < hide ? 'none' : ''; });
        var label = document.getElementById('msg-limit-label');
        if (label) label.textContent = 'of ' + total;
        rebuildTimeline();
      }
      window.applyMessageLimit = applyMessageLimit;
      setTimeout(function() { applyMessageLimit(200); }, 100);

      var promptIdx = -1;
      var _navLock = 0; // when >0, scroll handler won't override promptIdx
      function getVisiblePrompts() {
        return Array.from(document.querySelectorAll('.msg[data-role=""user""]'))
          .filter(function(el) { return el.offsetParent !== null; });
      }
      function updateCounter(prompts) {
        var el = document.getElementById('nav-counter');
        if (prompts.length === 0) { el.textContent = '- / -'; return; }
        el.textContent = (promptIdx + 1) + ' / ' + prompts.length;
      }
      function navPrompt(dir) {
        var prompts = getVisiblePrompts();
        console.log('[navPrompt] dir=' + dir + ' promptIdx=' + promptIdx + ' prompts=' + prompts.length + ' _navLock=' + _navLock);
        if (prompts.length === 0) return;
        _navLock++;
        document.querySelectorAll('.prompt-highlight').forEach(function(el) { el.classList.remove('prompt-highlight'); });
        promptIdx = Math.max(0, Math.min(prompts.length - 1, promptIdx + dir));
        prompts[promptIdx].scrollIntoView({behavior:'instant', block:'start'});
        prompts[promptIdx].classList.add('prompt-highlight');
        updateCounter(prompts);
        updateActiveMarker();
        console.log('[navPrompt] after: promptIdx=' + promptIdx);
        setTimeout(function() { _navLock--; console.log('[navPrompt] unlock, _navLock=' + _navLock); }, 100);
      }
      window.navPrompt = navPrompt;

      function navToFirst() {
        var prompts = getVisiblePrompts();
        console.log('[navToFirst] prompts=' + prompts.length + ' _navLock=' + _navLock);
        if (prompts.length === 0) return;
        _navLock++;
        promptIdx = 0;
        prompts[0].scrollIntoView({behavior:'instant', block:'start'});
        prompts[0].classList.add('prompt-highlight');
        updateCounter(prompts);
        updateActiveMarker();
        setTimeout(function() { _navLock--; console.log('[navToFirst] unlock'); }, 300);
      }
      window.navToFirst = navToFirst;
      function navToLast() {
        var prompts = getVisiblePrompts();
        console.log('[navToLast] prompts=' + prompts.length + ' _navLock=' + _navLock);
        if (prompts.length === 0) return;
        _navLock++;
        promptIdx = prompts.length - 1;
        prompts[promptIdx].scrollIntoView({behavior:'instant', block:'start'});
        prompts[promptIdx].classList.add('prompt-highlight');
        updateCounter(prompts);
        updateActiveMarker();
        console.log('[navToLast] set promptIdx=' + promptIdx);
        setTimeout(function() { _navLock--; console.log('[navToLast] unlock'); }, 300);
      }
      window.navToLast = navToLast;

      var bubbleIdx = -1;
      function navBubble(dir) {
        var msgs = Array.from(document.querySelectorAll('.msg'))
          .filter(function(el) { return el.offsetParent !== null; });
        if (msgs.length === 0) return;
        bubbleIdx = Math.max(0, Math.min(msgs.length - 1, bubbleIdx + dir));
        msgs[bubbleIdx].scrollIntoView({behavior:'smooth', block:'start'});
      }
      window.navBubble = navBubble;

      document.addEventListener('keydown', function(e) {
        if (e.altKey && e.key === 'ArrowUp') { e.preventDefault(); navPrompt(-1); }
        if (e.altKey && e.key === 'ArrowDown') { e.preventDefault(); navPrompt(1); }
        if (e.shiftKey && e.key === 'ArrowUp') { e.preventDefault(); navPrompt(-1); }
        if (e.shiftKey && e.key === 'ArrowDown') { e.preventDefault(); navPrompt(1); }
        if (!e.altKey && !e.shiftKey && !e.ctrlKey && !e.metaKey && e.key === 'ArrowUp') { e.preventDefault(); navBubble(-1); }
        if (!e.altKey && !e.shiftKey && !e.ctrlKey && !e.metaKey && e.key === 'ArrowDown') { e.preventDefault(); navBubble(1); }
        if ((e.ctrlKey || e.metaKey) && e.key === 'f') { e.preventDefault(); document.getElementById('search-box').focus(); }
      });

      function copyMsg(btn, mode) {
        var msgEl = btn.closest('.msg-cont') || btn.closest('.msg');
        if (!msgEl) return;
        var text = msgEl.dataset.text || '';
        var contentEl = msgEl.querySelector('.content');
        var html = contentEl ? contentEl.innerHTML : '';
        var done = function() {
          btn.classList.add('copied'); var orig = btn.textContent;
          btn.textContent = 'OK';
          setTimeout(function() { btn.classList.remove('copied'); btn.textContent = orig; }, 800);
        };
        if (mode === 'text') {
          var plain = text.replace(/\*\*(.+?)\*\*/g, '$1').replace(/`([^`]+)`/g, '$1');
          navigator.clipboard.writeText(plain).then(done);
        } else if (mode === 'md') {
          navigator.clipboard.writeText(text).then(done);
        } else if (mode === 'html') {
          var blob = new Blob([html], {type: 'text/html'});
          navigator.clipboard.write([new ClipboardItem({'text/html': blob})]).then(done);
        } else if (mode === 'rich') {
          var htmlBlob = new Blob([html], {type: 'text/html'});
          var textBlob = new Blob([text], {type: 'text/plain'});
          navigator.clipboard.write([new ClipboardItem({'text/html': htmlBlob, 'text/plain': textBlob})]).then(done);
        }
      }
      window.copyMsg = copyMsg;

      function getVisibleMessages() {
        return Array.from(document.querySelectorAll('.msg'))
          .filter(function(el) { return el.offsetParent !== null; });
      }
      function formatConversation(mode) {
        var msgs = getVisibleMessages();
        var title = document.querySelector('#titlebar h1');
        var titleText = title ? title.textContent : 'Conversation';
        var lines = [];
        if (mode === 'md') {
          lines.push('# ' + titleText + '\n');
          msgs.forEach(function(el) {
            var label = el.querySelector('.role') ? el.querySelector('.role').textContent : el.dataset.role || 'unknown';
            var text = el.dataset.text || el.querySelector('.content')?.textContent || '';
            lines.push('## ' + label + '\n'); lines.push(text + '\n'); lines.push('---\n');
          });
        } else if (mode === 'text') {
          lines.push(titleText + '\n');
          msgs.forEach(function(el) {
            var label = el.querySelector('.role') ? el.querySelector('.role').textContent : el.dataset.role || 'unknown';
            var text = el.dataset.text || el.querySelector('.content')?.textContent || '';
            lines.push('[' + label + ']'); lines.push(text + '\n');
          });
        } else if (mode === 'html') {
          var htmlParts = msgs.map(function(el) { return el.outerHTML; });
          return '<!DOCTYPE html><html><head><meta charset=""utf-8""></head><body>' + htmlParts.join('\n') + '</body></html>';
        }
        return lines.join('\n');
      }
      function copyConversation(mode) {
        var text = formatConversation(mode);
        if (mode === 'html') {
          var blob = new Blob([text], {type: 'text/html'});
          navigator.clipboard.write([new ClipboardItem({'text/html': blob})]);
        } else { navigator.clipboard.writeText(text); }
      }
      window.copyConversation = copyConversation;
      function saveConversation(mode) {
        var text = formatConversation(mode);
        var ext = mode === 'md' ? '.md' : mode === 'html' ? '.html' : '.txt';
        var mime = mode === 'html' ? 'text/html' : 'text/plain';
        var blob = new Blob([text], {type: mime});
        var a = document.createElement('a'); a.href = URL.createObjectURL(blob);
        a.download = 'conversation' + ext; a.click(); URL.revokeObjectURL(a.href);
      }
      window.saveConversation = saveConversation;

      var allCollapsed = false;
      function toggleCollapse() {
        allCollapsed = !allCollapsed;
        document.querySelectorAll('.msg-assistant .content').forEach(function(el) { el.classList.toggle('collapsed', allCollapsed); });
        document.querySelectorAll('.collapse-toggle').forEach(function(btn) { btn.textContent = allCollapsed ? 'Show more' : 'Show less'; });
      }
      window.toggleCollapse = toggleCollapse;
      document.addEventListener('click', function(e) {
        if (e.target.classList.contains('collapse-toggle')) {
          var content = e.target.previousElementSibling;
          if (!content) return;
          var isCollapsed = content.classList.toggle('collapsed');
          e.target.textContent = isCollapsed ? 'Show more' : 'Show less';
        }
      });
      setTimeout(function() {
        document.querySelectorAll('.msg-assistant .content').forEach(function(el) {
          if (el.scrollHeight > 200) {
            var btn = document.createElement('button'); btn.className = 'collapse-toggle';
            btn.textContent = 'Show less'; el.parentNode.insertBefore(btn, el.nextSibling);
          }
        });
      }, 50);

      var searchTimer;
      function doSearch(query) { clearTimeout(searchTimer); searchTimer = setTimeout(function() { executeSearch(query); }, 150); }
      window.doSearch = doSearch;
      function executeSearch(query) {
        document.querySelectorAll('mark.search-hit').forEach(function(m) { m.replaceWith(m.textContent); });
        document.querySelectorAll('.msg .content').forEach(function(el) { el.normalize(); });
        document.querySelectorAll('.search-match').forEach(function(el) { el.classList.remove('search-match'); });
        if (!query || query.length < 2) { document.body.classList.remove('search-active'); return; }
        document.body.classList.add('search-active');
        var re = new RegExp('(' + query.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + ')', 'gi');
        document.querySelectorAll('.msg .content').forEach(function(contentEl) {
          var container = contentEl.closest('.msg-cont') || contentEl.closest('.msg');
          var msgEl = contentEl.closest('.msg');
          var rawText = container.dataset.text || '';
          if (!re.test(rawText)) return;
          re.lastIndex = 0;
          msgEl.classList.add('search-match');
          highlightTextNodes(contentEl, re);
        });
      }
      function highlightTextNodes(el, re) {
        var walker = document.createTreeWalker(el, NodeFilter.SHOW_TEXT, {
          acceptNode: function(node) {
            if (node.parentNode.closest('pre,code')) return NodeFilter.FILTER_REJECT;
            return NodeFilter.FILTER_ACCEPT;
          }
        });
        var nodes = []; while (walker.nextNode()) nodes.push(walker.currentNode);
        nodes.forEach(function(textNode) {
          var text = textNode.textContent; if (!re.test(text)) return; re.lastIndex = 0;
          var frag = document.createDocumentFragment(); var lastIdx = 0; var match;
          while ((match = re.exec(text)) !== null) {
            if (match.index > lastIdx) frag.appendChild(document.createTextNode(text.slice(lastIdx, match.index)));
            var mark = document.createElement('mark'); mark.className = 'search-hit';
            mark.textContent = match[1]; frag.appendChild(mark); lastIdx = re.lastIndex;
          }
          if (lastIdx < text.length) frag.appendChild(document.createTextNode(text.slice(lastIdx)));
          textNode.parentNode.replaceChild(frag, textNode);
        });
      }

      var timelineEl = document.getElementById('timeline');
      var messagesEl = document.getElementById('messages');
      var tooltipEl = document.createElement('div');
      tooltipEl.className = 'tl-tooltip';
      if (timelineEl) timelineEl.appendChild(tooltipEl);
      function rebuildTimeline() {
        if (!timelineEl) return;
        Array.from(timelineEl.querySelectorAll('.marker')).forEach(function(m) { m.remove(); });
        var prompts = getVisiblePrompts();
        if (prompts.length === 0) return;
        var h = timelineEl.clientHeight;
        prompts.forEach(function(el, i) {
          var marker = document.createElement('div');
          marker.className = 'marker marker-user';
          marker.style.top = Math.round((i / prompts.length) * (h - 8)) + 'px';
          var rawText = el.dataset.text || '';
          var preview = rawText.substring(0, 200);
          if (rawText.length > 200) preview += '...';
          marker.dataset.preview = (el.dataset.ts || '') + '\n' + preview;
          marker.onmouseenter = function(e) {
            tooltipEl.textContent = marker.dataset.preview;
            var rect = marker.getBoundingClientRect();
            tooltipEl.style.top = rect.top + 'px'; tooltipEl.style.display = 'block';
          };
          marker.onmouseleave = function() { tooltipEl.style.display = 'none'; };
          marker.onclick = function() {
            _navLock++;
            promptIdx = i;
            console.log('[marker.click] i=' + i + ' promptIdx=' + promptIdx + ' total=' + prompts.length);
            document.querySelectorAll('.prompt-highlight').forEach(function(el) { el.classList.remove('prompt-highlight'); });
            el.scrollIntoView({behavior:'instant', block:'start'});
            el.classList.add('prompt-highlight');
            updateCounter(prompts); updateActiveMarker();
            setTimeout(function() { _navLock--; console.log('[marker.click] unlock'); }, 100);
          };
          timelineEl.appendChild(marker);
        });
        updateCounter(getVisiblePrompts());
      }
      function updateActiveMarker() {
        var markers = timelineEl.querySelectorAll('.marker');
        markers.forEach(function(m, i) { m.classList.toggle('active', i === promptIdx); });
      }
      (messagesEl || window).addEventListener('scroll', function() {
        requestAnimationFrame(function() {
          if (_navLock > 0) { console.log('[scroll] BLOCKED by _navLock=' + _navLock); return; }
          var prompts = getVisiblePrompts();
          if (prompts.length === 0) return;
          var best;
          var ct = messagesEl || document.documentElement;
          var scrollTop = ct.scrollTop;
          var scrollH = ct.scrollHeight;
          var clientH = ct.clientHeight;
          if (scrollTop <= 5) { best = 0; }
          else if (scrollTop + clientH >= scrollH - 20) { best = prompts.length - 1; }
          else {
            var viewTop = scrollTop + 100; best = 0;
            for (var i = 0; i < prompts.length; i++) { if (prompts[i].offsetTop <= viewTop) best = i; }
          }
          if (best !== promptIdx) {
            console.log('[scroll] override promptIdx ' + promptIdx + ' -> ' + best);
            promptIdx = best; updateCounter(prompts); updateActiveMarker();
          }
        });
      });
      var _followMode = false;
      function toggleFollow(on) {
        _followMode = on;
        if (on) {
          var m = messagesEl || document.documentElement;
          m.scrollTop = m.scrollHeight;
        }
      }
      window.toggleFollow = toggleFollow;

      // Auto-scroll when follow is on and content may have changed
      if (messagesEl) {
        new MutationObserver(function() {
          if (_followMode) messagesEl.scrollTop = messagesEl.scrollHeight;
        }).observe(messagesEl, {childList: true, subtree: true});
      }

      window.addEventListener('resize', rebuildTimeline);

      // On initial load, scroll to last message and select last marker
      setTimeout(function() {
        rebuildTimeline();
        navToLast();
      }, 200);
    })();
    </script>";
}
